### ISSUE TITLE
Junit report files are empty

### ISSUE THREAD

**Issue by JacobHearst** [alteral/fastlane-plugin-try_scan#20]
When I run this plugin against my project, the resulting junit report doesn't have any test suites or cases.

## Steps to reproduce:
1. Set up a new Xcode macOS project
    a. Create a new scheme for your UI testing target
    b. Under the "Test" section of that scheme, add the UI testing target
2. Run `fastlane init` in the project directory
3. Install the `try_scan` plugin
4. Configure the Fastfile to match the Fastfile below
5. run `fastlane ui_test`

## Expected behavior:
The file in `build/Tests/report.junit` contains entries for every test suite and case

## Actual behavior:
The file in `build/Tests/report.junit` contains the following:

    <?xml version='1.0' encoding='UTF-8'?>
    <testsuites tests='0' failures='0'/>

### Fastfile:

    default_platform(:mac)

    platform :mac do
      desc "Description of what the lane does"
      lane :ui_test do |options|
        options[:scheme] = "TestAppUITests"
        options[:output_directory] = "build/Tests"
        options[:output_types] = "junit"
        options[:fail_build] = false
        options[:try_count] = 2
        try_scan(options)
      end
    end

**Comment by alteral** [comment]
Hi @JacobHearst, thanks for reporting. [Here](https://github.com/fastlane/fastlane/issues/10276) is a rabbit hole. In short, [try_scan](https://github.com/alteral/fastlane-plugin-try_scan) relies on [scan](https://docs.fastlane.tools/actions/scan/), which depends on [xcpretty](https://github.com/xcpretty/xcpretty), which in turn causes this error.

If you need `junit` report, you can disable parallel testing:
```ruby
try_scan(try_parallel: false)
```

**Comment by Ramalike** [comment]
a small workaround. turn off the parallel_testing like `parallel_testing: false`. It's works for me
