### ISSUE TITLE
Test report files are overwritten by second run

### ISSUE THREAD

**Issue by JacobHearst** [alteral/fastlane-plugin-try_scan#21]
When I run this plugin against my project, everything works perfectly except that when it needs to retry tests, the original report is overwritten by the new one leaving me with a report containing only a few results. I debated a bit whether this was a problem for `xcpretty` or this project but ultimately decided to open an issue here because this is where the logic for retrying lives. Ideally I'd like a single, merged results file but separate results files would be good too.

## Steps to reproduce:
1. Set up a new Xcode macOS project
    a. Create a new scheme for your UI testing target
    b. Under the "Test" section of that scheme, add the UI testing target
2. Run `fastlane init` in the project directory
3. Install the `try_scan` plugin
4. Configure the Fastfile to match the Fastfile below
5. run `fastlane ui_tests`

## Expected behavior:
The file in `build/Tests/report.junit` contains entries for every test suite and case

## Actual behavior:
The file in `build/Tests/report.junit` contains only the results for tests that were re-run.

Here's an example from a project with ~100 tests that were run:

    <?xml version='1.0' encoding='UTF-8'?>
    <testsuites name='JamfConnectUITests.xctest' tests='4' failures='4'>
      <testsuite name='JamfConnectUITests.WelcomeWindowUITests' tests='4' failures='4'>
        <testcase classname='JamfConnectUITests.WelcomeWindowUITests' name='testDontShowCheckboxEnabled'>
          <failure message='Element StatusItem, {{1103.0, -23.0}, {28.0, 22.0}} is not hittable'>JamfConnectUITests/TestableDefaults/XCTestCaseDefaults.swift:45</failure>
        </testcase>
        <testcase classname='JamfConnectUITests.WelcomeWindowUITests' name='testDontShowCheckboxSavesState'>
          <failure message='Element StatusItem, {{1103.0, -23.0}, {28.0, 22.0}} is not hittable'>JamfConnectUITests/TestableDefaults/XCTestCaseDefaults.swift:45</failure>
        </testcase>
        <testcase classname='JamfConnectUITests.WelcomeWindowUITests' name='testLicenseWindowContents'>
      <failure message='Failed to get matching snapshot: No matches found for Elements matching predicate &apos;&quot;Licensed to: Jamf Testing '>JamfConnectUITests/WelcomeWindowUITests.swift:174</failure>
        </testcase>
        <testcase classname='JamfConnectUITests.WelcomeWindowUITests' name='testLoadBadLicense'>
          <failure message='XCTAssertTrue failed - The trial text should be visible when a bad license is installed.'>JamfConnectUITests/WelcomeWindowUITests.swift:127</failure>
        </testcase>
      </testsuite>
    </testsuites>

### Fastfile:

    default_platform(:mac)

    platform :mac do
      desc "Description of what the lane does"
      lane :ui_test do |options|
        options[:try_count] = 2
        options[:try_parallel] = false
        options[:output_directory] = "build/Tests"
        options[:derived_data_path] = "build/DerivedData"
        options[:fail_build] = false
        options[:scheme] = "TestAppUITests"
        try_scan(options)
      end
    end

**Comment by JacobHearst** [comment]
For anyone else encountering this issue, I was able to work around it with the following script

    #!/bin/sh
    chsum1=""
    reportCount=0

    while [[ true ]]
    do
        chsum2=`find build/Tests/ -type f -mtime -5s -name 'report*.junit' -exec md5 {} \;`
        if [[ $chsum1 != $chsum2 ]]; then
            if [[ -f build/Tests/report.junit ]]; then
                mv build/Tests/report.junit build/Tests/report-$reportCount.junit
                ((reportCount+=1))
            fi
            chsum1=$chsum2
        fi
        sleep 2
    done

Where `build/Tests` is the output directory for my reports and `report.junit` is the name of the report created by `xcpretty`

**Comment by alteral** [comment]
Hi @JacobHearst, thanks for reporting. I added a new option: `backup`. Check out the release `1.0.2`:

```ruby
try_scan(backup: true)
```

Please, let me know if you have any problems with a new version of `try_scan`.

**Comment by kvacquier** [comment]
I could not use the backup option on 1.0.2, it says it does not exist

**Comment by alteral** [comment]
Hey @kvacquier, thanks for raising this up. It sounds like you are not on `1.0.2`. Could you provide some additional information:
- Which command/arguments do you execute?
- Does your `Gemfile.lock` contain `fastlane-plugin-try_scan (1.0.2)`?
- Can you share the log?
